AllCops:
  Exclude:
    - 'assets/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.3

Layout/EndOfLine:
  EnforcedStyle: lf
Metrics/ClassLength:
  Max: 300
Metrics/MethodLength:
  Max: 30
Metrics/AbcSize:
  Max: 40
Style/MultilineBlockChain:
  Enabled: false
Metrics/BlockLength:
  Max: 50
# @todo #123:30m Needs to enable this check and fix all issues.
#  For now, this is out of the scope of this issue.
#  This issue appeared after update TargetRubyVersion to 2.3
Style/FrozenStringLiteralComment:
  Enabled: false
