assets:
  rubygems.yml: yegor256/home#assets/rubygems.yml
  s3cfg: yegor256/home#assets/s3cfg
install: |
  export GEM_HOME=~/.ruby
  export GEM_PATH=$GEM_HOME:$GEM_PATH
  sudo gem install pdd -v 0.20.5
  sudo gem install xcop -v 0.6
  bundle install
release:
  script: |-
    pdd -f /dev/null
    LC_ALL=US-ASCII bundle exec rake
    rm -rf *.gem
    sed -i "s/1\.0\.snapshot/${tag}/g" lib/pdd/version.rb
    git add lib/pdd/version.rb
    git commit -m "version set to ${tag}"
    gem build pdd.gemspec
    chmod 0600 ../rubygems.yml
    gem push *.gem --config-file ../rubygems.yml
    pdd --source=$(pwd) --verbose --file=pdd.xml -e=test/** -e=features/** -e=coverage/**/* -e=README.md
    s3cmd --no-progress put pdd.xml --config=../s3cfg s3://pdd.teamed.io/pdd.xml
    s3cmd --no-progress put assets/puzzles.xsd --acl-public --config=../s3cfg s3://pdd-xsd.teamed.io/${tag}.xsd
    s3cmd --no-progress put assets/puzzles.xsl --acl-public --config=../s3cfg s3://pdd-xsl.teamed.io/${tag}.xsl
merge:
  script: |-
    pdd -f /dev/null
    LC_ALL=US-ASCII bundle exec rake
deploy:
  script: |-
    echo 'Nothing to deploy'
    exit -1
